# Generated by Django 4.0.4 on 2023-07-11 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mypage', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='img_name',
            field=models.CharField(default='img_name', max_length=200),
        ),
    ]
